name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/*'
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/*'
      - 'README.md'
      - '.gitignore'

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install environment
      run: ./install.sh
    - name: Build
      run: ./build.sh
    - name: Test
      run: ./test.sh
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.GH_ACCESS_TOKEN }}
        repository: 'PTLux1517/Movilo'
